### ISSUE TITLE
HELP, pls!  R9 390 ETH - 16 MH.... V. 1.11...

### ISSUE THREAD

**Issue by EVGENY1777** [Lolliedieb/lolMiner-releases#71] opened 2020-10-21 07:28 UTC
Hello there! 

I use version 1.11 of Linux with driver 20.10. 

R9 390 ETH - 16 MH.... V. 1.11  

On other miners (Phoenix 5.1) -everything is fine, 30 MH. 

What should I do or what am I doing wrong?  

With respect.

**Comment by Lolliedieb** [comment] 2020-10-31 17:04
Well .. most likely the problem is on my side since I was not able to test my code on Hawaii cards yet ^^

**Comment by Lolliedieb** [comment] 2021-04-14 12:22
Fixed in 1.20 and newer

**Closed by Lolliedieb** 2021-04-14 12:22 UTC
