### ISSUE TITLE
AMD FirePro S10000 - zombie mode

### ISSUE THREAD

**Issue by 4miners** [Lolliedieb/lolMiner-releases#282] opened 2021-02-18 08:09 UTC
Hi,

I have some [AMD FirePro S10000 6GB](https://www.techpowerup.com/gpu-specs/firepro-s10000.c802) lying around, in lolMiner 1.24a they are detected as two [AMD FirePro W8000](https://www.techpowerup.com/gpu-specs/firepro-w8000.c586), unfortunately, they are not detected as zombie mode compatible. This card have two Tahiti cores with 3GB memory each and can mine ETC with about 48 MH/s combined while pulling ~420W, so not profitable at all. However, for ETH it would still be profitable for a while. Is there any chance to add support for this card and other workstation/server cards (I have some others but not tested them yet)?

Best regards,
Mariusz

**Comment by Lolliedieb** [comment] 2021-02-22 13:32
The problem is, that it is indeed only 2x 3 GB that sadly can not be used together - it acts as two cards with 3GB each on the same pcie slot. Atm it is not possible e.g. from core A to access the memory assigned to core B and vise versa. Thus Ethash does not fit this cards any more.

**Closed by Lolliedieb** 2021-02-22 13:32 UTC

**Comment by Chrobakk77** [comment] 2021-04-05 00:56
@4miners Hey there.
Bit offtopic but since you are one of few people with this card ...could you please share benchmark from Chukwa2? (TurtleCoin) and cryptonight_haven ? Would be super grateful since I can't find any data on this. 
Thanks!
